name: 'C++ CI'

on: 
  push:
    branches:
      - master

jobs:
  build_windows:
    runs-on: windows-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      
      # Установка SFML
      - name: Install SFML
        id: sfml
        uses: oprypin/install-sfml@v1
        with:
          sfml: 2.6.1  # Укажите нужную версию SFML
          config: Release
      
      # Настройка CMake
      - name: Configure CMake
        run: cmake . -DPATCH_VERSION=${{ github.run_number }} -DSFML_DIR="${{ steps.sfml.outputs.path }}"
      
      # Сборка проекта
      - name: Build project
        run: cmake --build .

      # Проверка наличия файлов после сборки
      - name: List files after build (windows)
        run: dir

      # Создание пакета
      - name: Create package (windows)
        run: cmake --build . --target package

      # Проверка наличия zip-файла перед загрузкой
      - name: Check for package file (windows)
        run: |
          if (Test-Path "./physics-0.0.${{ github.run_number }}-win64.zip") {
            Write-Host "Package exists."
          } else {
            Write-Host "Package does not exist."
            exit 1
          }

      # Создание релиза и загрузка артефактов
      - name: Create Release (windows)
        id: create_release_windows
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: windows${{ github.run_number }}
          release_name: Release ${{ github.run_number }} (windows)
          draft: false
          prerelease: false

      - name: Upload Release Asset (windows)
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_windows.outputs.upload_url }}
          asset_path: ./physics-0.0.${{ github.run_number }}-win64.zip  # Убедитесь, что этот путь правильный
          asset_name: physics-0.0.${{ github.run_number }}-win64.zip
          asset_content_type: application/zip
  
  build_ubuntu:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      
      # Установка SFML на Ubuntu (можно использовать apt-get)
      - name: Install SFML on Ubuntu
        run: sudo apt-get install libsfml-dev
      
      # Настройка CMake для Ubuntu
      - name: Configure CMake (ubuntu)
        run: cmake . -DPATCH_VERSION=${{ github.run_number }}

      # Сборка проекта на Ubuntu
      - name: Build project (ubuntu)
        run: cmake --build .

      # Проверка наличия файлов после сборки на Ubuntu
      - name: List files after build (ubuntu)
        run: ls -la

      # Создание пакета для Ubuntu
      - name: Create package (ubuntu)
        run: cmake --build . --target package

      # Проверка наличия zip-файла перед загрузкой на Ubuntu
      - name: Check for package file (ubuntu)
        run: |
          if [ -f "./physics-0.0.${{ github.run_number }}-Linux.zip" ]; then
            echo "Package exists."
          else
            echo "Package does not exist."
            exit 1
          fi

      # Создание релиза и загрузка артефактов для Ubuntu
      - name: Create Release (ubuntu)
        id: create_release_ubuntu
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ubuntu${{ github.run_number }}
          release_name: Release ${{ github.run_number }} (ubuntu)
          draft: false
          prerelease: false 

      - name: Upload Release Asset (ubuntu)
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_ubuntu.outputs.upload_url }}
          asset_path: ./physics-0.0.${{ github.run_number }}-Linux.zip  # Убедитесь, что этот путь правильный
          asset_name: physics-0.0.${{ github.run_number }}-Linux.zip
          asset_content_type: application/zip